version: '3'
services:
  app:
    build: ./docker/php
    ports:
      - 80:80
      - 5173:5173
    command: bash -c "php-fpm && httpd -D FOREGROUND"
    volumes:
      - type: bind
        source: ./zhd-info-app
        target: /var/www/zhd-info-app
    working_dir: /var/www/zhd-info-app
    depends_on:
      - db
    
  db:
    build: ./docker/mysql
    platform: linux/x86_64
    command: mysqld --innodb_use_native_aio=0 --character-set-server=utf8mb4  --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: zhduser
      MYSQL_PASSWORD: zhdpass
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/mysql/init
        target: /docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  mysql-volume:
    name: zhd-info-data