version: '3'
services:
  app:
    build: ./docker/php
    ports:
      - 80:80
    command: bash -c "php-fpm && httpd -D FOREGROUND"
    volumes:
      - type: bind
        source: ./zhd-info-app
        target: /var/www/zhd-info-app
    depends_on:
      - db
    
  db:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/mysql/init
        target: /docker-entrypoint-initdb.d
    ports:
      - 3306:3306

volumes:
  mysql-volume:
    name: php-data