version: '3'
services:
  app:
    build: ./docker/php
    ports:
      - 80:80
      - 5173:5173
    # command: bash -c "php-fpm && httpd -D FOREGROUND"
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    volumes:
      - type: bind
        # source: ./zhd-info-app
        source: \\wsl.localhost\Ubuntu-22.04\home\yushi\workspace\zhd-info/zhd-info-app
        target: /var/www/zhd-info-app
    working_dir: /var/www/zhd-info-app
    depends_on:
      - db

  db:
    build: ./docker/mysql
    platform: linux/x86_64
    command: mysqld --innodb_use_native_aio=0 --character-set-server=utf8mb4  --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: zhduser
      MYSQL_PASSWORD: zhdpass
      TZ: 'Asia/Tokyo'
    volumes:
      - type: volume
        source: mysql-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/mysql/init
        target: /docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  db-test:
    build: ./docker/mysql
    platform: linux/x86_64
    command: mysqld --innodb_use_native_aio=0 --character-set-server=utf8mb4  --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: zhduser
      MYSQL_PASSWORD: zhdpass
      TZ: 'Asia/Tokyo'
    volumes:
      - type: bind
        source: ./docker/mysql/init
        target: /docker-entrypoint-initdb.d
    ports:
      - 3360:3306

  minio :
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    container_name: minio
    ports:
      - "9090:9000"
      - "9091:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - type: bind
        source: ./docker/minio/data
        target: /export
volumes:
  mysql-volume:
    name: zhd-info-data