FROM mysql/mysql-server

COPY ./config/my.cnf /etc/my.cnf
# RUN dnf update -y

# RUN dnf -y localinstall  https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
# RUN dnf -y install mysql mysql-community-client
# RUN yum install -y mysql mysql-devel

# RUN mysqld start